### ISSUE TITLE
Table in text document

### ISSUE THREAD

**Issue by btrd** [T0ha/ezodf#10]
Is it possible to add a table in a text document ? I don't find any information in the documentation

**Comment by T0ha** [comment]
Hi btrd,
Table object is usable either in ODT or in ODS files. Seems you can try to use it. If any trouble, pls, write it here. Thanks.

**Comment by T0ha** [comment]
Hi btrd,
Am I right that previous comment solved your issue? Can I close it?

**Comment by btrd** [comment]
Yes you can, thanks :)
