### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by fuhrysteve** [T0ha/ezodf#11]
Could someone please tag a release? There hasn't been one since December, and `0.3.0` has issues with python3.

Even just a `0.3.1` on github would be helpful https://github.com/T0ha/ezodf/releases

Thanks!

**Comment by T0ha** [comment]
I'll make a minor build today

**Comment by fuhrysteve** [comment]
Thanks! It'll just be a lot more readable and less confusing as a dependency to have a version number instead of a [commit hash](https://github.com/chfw/Flask-Excel/blob/master/tests/requirements.txt#L14).

**Comment by chfw** [comment]
It'll be great if latest ezodf could be published to pypi.

**Comment by chfw** [comment]
it is really cumbersome to obtain ezodf 0.3.1 if it is not in pypi. Can we have one in pypi soon? This is a one year old request :'(

**Comment by T0ha** [comment]
Hi falks,
Sorry for not deploying for long time. I was a bit overloaded. Now 0.3.2 is there (not 3.1 as pypi have some troubles with reuploading releases)
