### ISSUE TITLE
ODS: Add rows and columns automatically

### ISSUE THREAD

**Issue by dablak** [T0ha/ezodf#14]
Hi, this is more a nice to have enhancement request than an issue.

Is it possible/easy for spreadsheets to create columns and rows automatically when adding a value instead of raising an index out of range error?

For example:

``` python
sheet = ezodf.Table('Sheet')
print(sheet.nrows(), sheet. ncols())
#0 0
sheet[10, 20].set_value('A value')
print(sheet.nrows(), sheet. ncols())
#10 20
```

Cheers

**Comment by chfw** [comment]
+1, odfpy supports this while ezodf wants to the columns and rows in advance. In some situations, the developer just dont know and is forced to find out them first before continuing.
